### ISSUE TITLE
Allow to reflect empty interfaces

### ISSUE THREAD

**Issue by stepancar** [pcan/reflec-ts-examples#1]
remove all properties from your test interface in your inspect-interface example and then compile and run.

see runtime exception

**Comment by stepancar** [comment]
I'm sory, this issue for reflect-ts

**Comment by pcan** [comment]
No problem, I'll file them in reflec-ts project :+1:

**Comment by pcan** [comment]
Ok, I have checked this and works as expected. The example lacks of a null-check on the `members` field, that in this case is not defined and it's correct since it's not mandatory. See [here](https://github.com/pcan/reflec-ts/blob/master/src/lib/reflection.d.ts#L143) for details about the `Interface` type. I'm going to fix the example.

**Comment by pcan** [comment]
Examples fixed.
