### ISSUE TITLE
Hitting a TS2693 error

### ISSUE THREAD

**Issue by iranicus** [pcan/reflec-ts-examples#5]
Hello, I seem to be hitting a TS2693 error complaining about using a type as a value when I pass in the interface in the isValid function for the second argument which is stopping my code from compiling, I followed the example you have posted and seem to be stuck on this. I am eager to get this working since it is exactly what I have been looking for for awhile with making sure the object I receive in an api response contains exactly the same data and data types as I expect following an interface, and to inform of any extra properties present or discrepancies of the existing properties.

**Comment by pcan** [comment]
Hi, it seems TS2693 is related to `Promise` type. Since reflec-ts project has been in stand-by for some time (see [this note](https://github.com/pcan/reflec-ts#reflec-ts)), it may not fully support the latest language updates (Promises, async functions, generators and so on). The current  reflec-ts version is aligned with TypeScript v2.2.1 and I don't remember how this version supports `Promise` type. 
Could you post a sample code and your `tsconfig.json` content?

**Comment by iranicus** [comment]
Sure can do, so for my tsconfig.json I have:
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom",
      "es5"
    ]
  }
}
```

And where I use the isValid function:
```
  ngOnInit() {
    this.dataRetrievalService.getPersonDetails().subscribe(
      (data: Person) => {
        console.log('incoming data', data);

        // JSON object check
        console.log('is data valid? ' + isValid(data, IPerson));
});
```

```
export interface IPerson {
  fName: string;
  lName: string;
}
```

**Comment by iranicus** [comment]
I did notice that in the tsconfig on the reflec.ts page that they included "reflectionEnabled": true in which I have added in too just now.

**Comment by pcan** [comment]
Ok, I would add just two things for the sake of clarity:
- You may try to change `"target": "es5"` to `"target": "es6"`. I read somewhere on StackOverflow that this solves TS2693.
- Please note that `reflectionEnabled` is not a standard TypeScript compiler parameter, but an extension introduced by reflec-ts (that is not controlled/approved by Microsoft) that enables the usage of classes/interfaces as constant literals (beyond their usual _compile-time-only_ capabilities).

If this solved your error you may close this issue. Thanks for your interest 😃

**Comment by iranicus** [comment]
Yeah I have been messing around with the target with adding extras and changing them already but to no avail : < It now currently is set to es6 but seems like the issue still stands. I've been reading around that type guards could essentially used for this sort of functionality I am after so I'll take a look into using them for the moment. Thanks

**Comment by pcan** [comment]
Ok, so the last thing that comes to my mind is the core compiler itself. I see you are writing a `ngOnInit()` and I guess you are trying to work with Angular (v.6?). Furthermore you are using arrow syntax `() => ...` and  importing `es2017` types: these features have not been checked against my reflec-ts compiler, since I stopped merging the official compiler code updates some time ago. Please try to write a test project from scratch that only includes reflec-ts, your `IPerson` interface and your code snipped without any other dependency:
```Typescript
function check(data: Person) {
        console.log('incoming data', data);

        // JSON object check
        console.log('is data valid? ' + isValid(data, IPerson));
}
```

tsconfig.json:
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es6",
  },
  "reflectionEnabled": true
}
```

If this works, it means the problem cannot be solved (I think Angular 6 cannot work properly with reflec-ts and TypeScript compiler together), and we have to wait TypeScript team decisions about compiler plugins, type serialization format and other topics, as I reported in reflec-ts project readme file. 
Please upvote those issues in the official TypeScript github project: if many people ask support about reflection and/or compiler plugin customization, the core team might prioritize decisions and efforts in that direction.

**Comment by iranicus** [comment]
Hello there, unfortunately having tested this it hasn't solved the problem, it was intended to be used with in a Angular 3 project however where es6 arrow syntax is used a lot, I will upvote it in the typescript github project however as I would be eager for it to be supported. Thanks for your help.
